logging-to-file = false        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/MatadorProBr/revanced-extended-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "inotia00/revanced-patches"
build-mode = "module"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "inotia00 ReVanced"
included-patches = "'Hide voice search button' 'Premium heading'"
excluded-patches = "'Alternative thumbnails' 'Append time stamps information' 'Change start page' 'Custom branding icon YouTube' 'Custom double tap length' 'Custom player overlay opacity' 'Custom seekbar color' 'Enable gradient loading screen' 'Enable new splash animation' 'Enable new thumbnail preview' 'Enable wide search bar' 'Hide category bar' 'Hide channel avatar section' 'Hide channel profile components' 'Hide crowdfunding box' 'Hide description components' 'Hide seekbar' 'Hide time stamp' 'Hide trending searches' 'Theme' 'Translations'"

